apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  namespace: development
spec:
  selector:
    matchLabels:
      app: auth
  replicas: 1
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: ghcr.io/bright-co/bright-resume-back-auth:2954bc7e0249b0913a2481fcb707ad0c28ece31f
        ports:
          - containerPort: 4001
        env:
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-auth-password
              key: password
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: google-client-secret
              key: secret
        - name: GITHUB_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: github-client-secret
              key: secret
        - name: LINKEDIN_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: linkedin-client-secret
              key: secret
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: secret
        - name: MONGO_URL
          value: mongodb://root:$(MONGODB_PASSWORD)@mongo-auth-service:27017/?authMechanism=DEFAULT
        envFrom:
        - configMapRef:
            name: auth-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: development
spec:
  selector:
    app: auth
  ports:
  - port: 80
    protocol: TCP
    targetPort: 4001
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-configmap
  namespace: development
data:
  DATABASE_NAME: auth
  SERVER_URL: https://auth-development.bright-resume.com
  CLIENT_AUTH_URL: https://development.bright-resume.com/auth/sign-in-oauth
  GOOGLE_CLIENT_ID: 437856812561-4s350dtpl84e0emjqce0mgftd9d8m7nh.apps.googleusercontent.com
  GITHUB_CLIENT_ID: 866f10fb0baf4d5d1c11
  LINKEDIN_CLIENT_ID: 77ms4asm9fy0ee
