apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  namespace: development
spec:
  selector:
    matchLabels:
      app: auth
  replicas: 1
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: ghcr.io/bright-co/bright-resume-back-auth:f2ea52ac7aa72582f9feb528504f9ea940476078
        ports:
          - containerPort: 4001
        env:
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-auth-password
              key: password
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: secret
        - name: MONGO_URL
          value: mongodb://root:$(MONGODB_PASSWORD)@mongo-auth-service:27017/?authMechanism=DEFAULT
        envFrom:
        - configMapRef:
            name: auth-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: development
spec:
  selector:
    app: auth
  ports:
  - port: 80
    protocol: TCP
    targetPort: 4001
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-configmap
  namespace: development
data:
  DATABASE_NAME: auth
  GOOGLE_CLIENT_ID: GOOGLE_CLIENT_ID
  GOOGLE_CLIENT_SECRET: GOOGLE_CLIENT_SECRET
  SERVER_URL: SERVER_URL
