apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-deployment
  namespace: development
spec:
  selector:
    matchLabels:
      app: chatbot
  replicas: 3
  template:
    metadata:
      labels:
        app: chatbot
    spec:
      containers:
      - name: chatbot
        image: ghcr.io/bright-co/bright-resume-chatbot:23cc6857f38a684c3f325fc911149ef06e44955a
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: chatbot-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: chatbot-service
  namespace: development
spec:
  selector:
    app: chatbot
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: chatbot-configmap
  namespace: development
data:
  MODE: develop
  BACK_URL: https://back-development.bright-resume.com
