apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms-deployment
  namespace: development
spec:
  selector:
    matchLabels:
      app: cms
  replicas: 1
  template:
    metadata:
      labels:
        app: cms
    spec:
      containers:
      - name: cms
        image: ghcr.io/bright-co/bright-resume-back-cms:f7c4afa327ac06f87dbe2f49595938d07304ba86
        ports:
          - containerPort: 4004
        env:
        - name: APP_KEYS
          valueFrom:
            secretKeyRef:
              name: cms-keys
              key: keys
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-cms-password
              key: password
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: cms-jwt-secret
              key: secret
        - name: ADMIN_JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: cms-admin-jwt-secret
              key: secret
        - name: TRANSFER_TOKEN_SALT
          valueFrom:
            secretKeyRef:
              name: cms-transfer-token-salt
              key: salt
        - name: API_TOKEN_SALT
          valueFrom:
            secretKeyRef:
              name: cms-api-token-salt
              key: salt
        envFrom:
        - configMapRef:
            name: cms-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: cms-service
  namespace: development
spec:
  selector:
    app: cms
  ports:
  - port: 80
    protocol: TCP
    targetPort: 4004
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cms-configmap
  namespace: development
data:
  PORT: '4004'
  API_TOKEN_SALT: API_TOKEN_SALT
  DATABASE_NAME: cms
  DATABASE_HOST: postgres-cms-service
  DATABASE_CLIENT: postgres
  DATABASE_USERNAME: root
  DATABASE_PORT: '5432'