apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  namespace: development
spec:
  selector:
    matchLabels:
      app: gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: ghcr.io/bright-co/bright-resume-back-gateway:675d4ab403e73da39249ea0dd472014520f78f1a
        ports:
          - containerPort: 4000
        envFrom:
        - configMapRef:
            name: gateway-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: development
spec:
  selector:
    app: gateway
  ports:
  - port: 80
    protocol: TCP
    targetPort: 4000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-configmap
  namespace: development
data:
  RESUME_URL: http://resume-service:80/graphql
  AUTH_URL: http://auth-service:80/graphql
  FILE_URL: http://file-service:80/graphql
