apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: index-certificate
  namespace: development
spec:
  dnsNames:
    - back-development.bright-resume.com
    - cms-development.bright-resume.com
    - auth-development.bright-resume.com
    - development.bright-resume.com
  secretName: index-certificate-secret
  issuerRef:
    name: index-cluster-issuer-development
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: index-cluster-issuer-development
  namespace: development
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: erfan@bright-resume.com
    privateKeySecretRef:
      name: letsencrypt-cluster-issuer-key
    solvers:
    - http01:
       ingress:
         class: nginx
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: index-ingress
  namespace: development
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  tls:
  - hosts:
    - back-development.bright-resume.com
    - cms-development.bright-resume.com
    - auth-development.bright-resume.com
    - development.bright-resume.com
    secretName: index-certificate-secret
  rules:
  - host: back-development.bright-resume.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: gateway-service
            port: 
              number: 80
  - host: cms-development.bright-resume.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: cms-service
            port: 
              number: 80
  - host: auth-development.bright-resume.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: auth-service
            port: 
              number: 80
  - host: development.bright-resume.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: web-service
            port: 
              number: 80