apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-resume
  namespace: staging
spec:
  serviceName: mongo-resume-service-headless
  replicas: 1
  selector:
    matchLabels:
      app: mongo-resume
  template:
    metadata:
      labels:
        app: mongo-resume
    spec:
      containers:
      - name: mongo-resume
        image: mongo:latest
        ports:
        - containerPort: 27017
          name: mongo
        volumeMounts:
        - name: mongo-resume-data
          mountPath: /data/db
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-resume-password
              key: password
      volumes:
      - name: mongo-resume-data
        persistentVolumeClaim:
          claimName: mongo-resume-data-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-resume-data-pvc
  namespace: staging
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  volumeName: mongo-resume-pv-staging
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-resume-service
  namespace: staging
spec:
  selector:
    app: mongo-resume
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-resume-service-headless
  namespace: staging
spec:
  selector:
    app: mongo-resume
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  clusterIP: None