apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-file-pv-production
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /k8s-mongo-file-pv-production
