apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-cms-pv-production
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /k8s-postgres-cms-pv-production
