apiVersion: v1
kind: Service
metadata:
  name: postgres-cms-service-internal
  namespace: production
spec:
  selector:
    app: postgres-cms
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-cms-data-pvc
  namespace: production
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  volumeName: postgres-cms-pv-production
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-cms-configmap
  namespace: production
data:
  POSTGRES_USER: root
  POSTGRES_DB: cms
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-cms
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-cms
  serviceName: postgres-cms-service-internal
  template:
    metadata:
      labels:
        app: postgres-cms
    spec:
      containers:
      - name: postgres-cms
        image: postgres:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-cms-password
              key: password
        envFrom:
        - configMapRef:
            name: postgres-cms-configmap
        volumeMounts:
        - name: postgres-cms-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-cms-data
        persistentVolumeClaim:
          claimName: postgres-cms-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-cms-service
  namespace: production
spec:
  selector:
    app: postgres-cms
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432