apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/bright-co/bright-resume-gitops.git
    targetRevision: HEAD
    path: staging
  destination: 
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
