apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-back-pv-development
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /k8s-mongo-back-pv-development
